---
layout: cv
title: Chase Box's Resume
---
# Chase Box
Computer Science Student | Java & Web Developer

<div id="webaddress">
<a href="mailto:chasioboxio@gmail.com">chasioboxio@gmail.com</a>
| (417) 413-8820
| <a href="https://www.linkedin.com/in/chase-box-46a3853a7">LinkedIn</a>
| <a href="https://github.com/ChaseB-creator">GitHub</a>
</div>

## Education

`July 2025 - July 2027`
__Bachelor's of Computer Science__, Brigham Young University - Idaho, Rexburg, Idaho

- Currently holding a 3.95 / 4.0 GPA.
- Cooperated in collaborative team projects and conducted informational interviews with industry professionals.

`August 2020 - May 2024`
__Associate's of Arts Degree__, Ozark Technical Community College, Springfield, Missouri

- Graduated with a GPA higher than 3.5 / 4.0.
- Mentored beginner programmers and assisted peers with C# concepts.


## Career Experience

`5 Months (Present)`
__Campus Custodian__, Brigham Young University - Idaho, Rexburg, Idaho

- Engaged communication skills, team coordination, team correspondence, leadership, and helping others.
- Maintained campus cleanliness as part of a 7-person team, demonstrating consistency and reliability.


## Skills

- Problem identification and efficient, solution-oriented thinking through teamwork and active communication.
- Technical collaborator; works well in team environments.
- Specializes in Java development, web development, and frontend/backend application development.
- Proficient in HTML, CSS, and JavaScript.


## Projects

`September 2025 - November 2025`
__Crypto Miner__

- Led design and development of an idle game using HTML, CSS, JavaScript, and Rust.
- Coordinated a 4-person team over a 14-week development cycle.

`April 2024 - May 2024`
__Java School Database__

- Designed a relational database in Java using NetBeans to manage student and staff records.
- Incorporated instructor feedback to refine and complete the project.


## Awards

- Obtained Associate's of Arts degree upon graduation from Ozark Technical Community College, May 2024; transferred credits to Brigham Young University - Idaho, July 2025.
- Received A+ Scholarship in recognition of peer tutoring contributions.


## Languages

- English (native)
- Spanish (4+ years of study; led and facilitated peers in learning Spanish)
- French (currently learning)


<!-- ### Footer

Last updated: March 2026 -->
